default: &default
  adapter: <%= ENV.fetch("RAILS_DB_ADAPTER", 'postgresql') %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username:  <%= ENV.fetch("POSTGRES_USER",'root') %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD",'root') %>
  database: <%= ENV.fetch("POSTGRES_DB",'dev') %>
  host: <%= ENV.fetch("POSTGRES_HOST",'0.0.0.0') %>
  port: <%= ENV.fetch("POSTGRES_PORT"){ `docker-compose port db 5432`.strip.match(/[0-9]+$/)[0] rescue "5432"} %>

development:
  <<: *default

test:
  <<: *default
  database: web_site_test

production:
  <<: *default
